apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamator.fullname" . }}-api
  namespace: {{ include "llamator.namespace" . }}
  labels:
    {{- include "llamator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llamator.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "llamator.fullname" . }}-api
        {{- include "llamator.labels" . | nindent 8 }}
    spec:
{{- if .Values.api.hostAliases }}
      hostAliases:
{{ toYaml .Values.api.hostAliases | nindent 8 }}
{{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}

          command:
            - uvicorn
            - llamator_mcp_server.main:app
            - --host
            - {{ .Values.api.env.LLAMATOR_MCP_HTTP_HOST | quote }}
            - --port
            - {{ .Values.api.env.LLAMATOR_MCP_HTTP_PORT | quote }}
            - --log-level
            - {{ .Values.api.env.LLAMATOR_MCP_UVICORN_LOG_LEVEL | quote }}

          env:
            # non-secret values
          {{- range $name, $value := .Values.api.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
          {{- end }}

            # OpenAI attack model config
            - name: LLAMATOR_MCP_ATTACK_OPENAI_BASE_URL
              value: {{ .Values.openai.attack.baseUrl | quote }}
            - name: LLAMATOR_MCP_ATTACK_OPENAI_MODEL
              value: {{ .Values.openai.attack.model | quote }}
            - name: LLAMATOR_MCP_ATTACK_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.attack.secret.name }}
                  key: {{ .Values.openai.attack.secret.key }}


              # OpenAI judge model config
            - name: LLAMATOR_MCP_JUDGE_OPENAI_BASE_URL
              value: {{ .Values.openai.judge.baseUrl | quote }}
            - name: LLAMATOR_MCP_JUDGE_OPENAI_MODEL
              value: {{ .Values.openai.judge.model | quote }}
            - name: LLAMATOR_MCP_JUDGE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.judge.secret.name }}
                  key: {{ .Values.openai.judge.secret.key }}

            # OpenAI target model config
            - name: LLAMATOR_MCP_TARGET_OPENAI_BASE_URL
              value: {{ .Values.openai.target.baseUrl | quote }}
            - name: LLAMATOR_MCP_TARGET_OPENAI_MODEL
              value: {{ .Values.openai.target.model | quote }}
            - name: LLAMATOR_MCP_TARGET_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.target.secret.name }}
                  key: {{ .Values.openai.target.secret.key }}

          volumeMounts:
            - name: artifacts
              mountPath: {{ .Values.api.volumeMounts.artifactsPath }}
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: artifacts
{{- if .Values.artifactsVolume.useEmptyDir }}
          emptyDir: {}
{{- else if .Values.artifactsVolume.persistentVolumeClaim.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "llamator.fullname" . }}-artifacts-pvc
{{- else }}
          emptyDir: {}
{{- end }}
